algoritmo "Nome do Programa"

var
Nome: caractere 
salarioAtual, salarioAumento :real 
 



inicio

    escreval("Digite seu nome :")
    leia(nome)
    escreval ("Olá ", nome," digite o valor do seu salário atual :")
    leia(salarioAtual)

        salarioAumento <- salarioAtual + (salarioAtual * 0.10)

    escreval("Sr(a)", nome, " voce teve um aumento de 10% e seu novo salário é R$:", salarioAumento)




fimalgoritmo