algoritmo "Nome do Programa"

var
i, j : inteiro 
qualquerCoisa: caractere



inicio
i<- 2
j <- 0
enquanto (i <> j) faca
    escreval ("Digite qualquer coisa :")
    leia(qualquerCoisa)
    escreval("ALERTA!!!, VOCE DIGITOU :", qualquerCoisa," O PROGRAMA ESTÁ EM LOOP ATÉ VC DIGITAR 0 ")

        se (qualquerCoisa = "0") entao
            j<- i

            escreval("PROGRAMA ENCERRADO ")
        
        fimse
fimenquanto



fimalgoritmo