algoritmo "questao26"

var
media897, media456, somaMedia: real 
mediaDasMedias: real 



inicio

media897 <- (8+9+7)/3
media456 <- (4+5+6)/3
somaMedia <- media897 +media456
mediaDasMedias <- (media897 +media456)/2
escreval("A media aritimética dos numeros 8 ,9 e 7 é : ", media897)
escreval("A media aritimética dos numeros 4 ,5 e 6 é : ", media456)
escreval("A soma das médias é :", somaMedia)
escreval("A média das médias é :", mediaDasMedias)



fimalgoritmo